# 1. Imagen base de Python
FROM python:3.10-slim

# 2. Establecer el directorio de trabajo
WORKDIR /app

# 3. Copiar solo el archivo de requisitos
COPY requirements.txt .

# 4. Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copiar el resto del código

COPY . .

# 6. Comando para ejecutar la aplicación

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000"]