# 1. Imagen base
FROM python:3.11-slim

# 2. Directorio de trabajo
WORKDIR /app

# 3. Instalar dependencias
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 4. Copiar el código de la aplicación
COPY ./app /app/app

# 5. Comando para iniciar el worker
# Simplemente ejecuta el script de Python
CMD ["python", "-m", "app.worker"]