# 1. Imagen base de Python
FROM python:3.11-slim

# 2. Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# 3. Copiar solo el archivo de requisitos e instalar dependencias
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# --- INICIO DE LA CORRECCIÓN ---
# 4. Copiar TODO el código necesario
COPY ./app /app/app
COPY ./alembic.ini .
COPY ./alembic /app/alembic
# --- FIN DE LA CORRECCIÓN ---

# 5. Exponer el puerto en el que correrá Uvicorn
EXPOSE 8001

# 6. Comando para iniciar el servidor
# El 'host 0.0.0.0' es crucial para que sea accesible desde fuera del contenedor
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]