"""Crear tabla transactions

Revision ID: abe4985bdd08
Revises: 
Create Date: 2025-11-01 19:37:56.718424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe4985bdd08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_origen', sa.String(length=50), nullable=True),
    sa.Column('cuenta_destino', sa.String(length=50), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('hora', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'NORMAL', 'SUSPICIOUS', 'BLOCKED', name='transactionstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_cuenta_destino'), 'transactions', ['cuenta_destino'], unique=False)
    op.create_index(op.f('ix_transactions_cuenta_origen'), 'transactions', ['cuenta_origen'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_cuenta_origen'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_cuenta_destino'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
